### ISSUE TITLE
Wrong source-url in META6.json

### ISSUE THREAD

**Issue by niner** [gotoexit/Concurrent-BoundedChannel#4]
The repository pointed to by the source-url in the META6.json seems to have been renamed. This prevents installation of your distribution.

**Comment by gotoexit** [comment]
I think this was originally a copy-paste job from another module.  Must have overlooked the url.  Fixed in [v0.4.0](https://github.com/gotoexit/Concurrent-BoundedChannel/releases/tag/v0.4.0).
